import React,{useEffect,useMemo,useState} from 'react';
import {Alert,Modal,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {api} from './api';
import {getPng} from './export';
import {colors} from './theme';
import {Btn,Card,Chip,ErrorBox,HScroll,Metric,Muted,Pill,ToggleRow} from './ui';

type Tab='ranking'|'records'|'players'|'teams'|'finance'|'history';
const tabs:{k:Tab;l:string}[]=[
 {k:'ranking',l:'Ranking'},{k:'records',l:'Rekordy'},{k:'players',l:'Gracze'},
 {k:'teams',l:'Drużyny i strzelcy'},{k:'finance',l:'Rozliczenia'},{k:'history',l:'Historia'}
];
const fmtDate=(x:any)=>{const s=String(x||'').slice(0,10);if(!s)return '—';const a=s.split('-');return a.length===3?`${a[2]}.${a[1]}.${a[0]}`:s};
const nameVal=(x:any,key='value',suffix='')=>x?.name?`${x.name} — ${x[key]??'—'}${suffix}`:'—';

function Ranking({open}:{open:(id:string)=>void}){
 const [d,setD]=useState<any>(null),[e,setE]=useState('');
 useEffect(()=>{api.playerStats().then(setD).catch(x=>setE(x.message))},[]);
 return <View style={{gap:9}}>{e?<ErrorBox message={e}/>:null}{(d?.players||[]).map((p:any,i:number)=><Pressable key={p.player_id} onPress={()=>open(p.player_id)}><Card style={s.rank}><Text style={s.rankNo}>{i+1}</Text><View style={{flex:1}}><Text style={s.name}>{p.name}</Text><Text style={s.sub}>{p.matches} meczów • {p.w}W {p.d}R {p.l}P • {p.gf}:{p.ga}</Text></View><View><Text style={s.titleNo}>🏆 {p.titles}</Text><Text style={s.win}>{p.win_pct}% W</Text></View></Card></Pressable>)}</View>;
}

function Rec({icon,title,value,sub}:{icon:string;title:string;value:string;sub?:string}){return <Card><View style={s.recordHead}><Text style={s.recordIcon}>{icon}</Text><View style={{flex:1}}><Text style={s.cardTitle}>{title}</Text><Text style={s.recordValue}>{value}</Text>{sub?<Text style={s.sub}>{sub}</Text>:null}</View></View></Card>}
function Records(){
 const [d,setD]=useState<any>(null),[e,setE]=useState('');useEffect(()=>{api.records().then(setD).catch(x=>setE(x.message))},[]);const r=d?.records||{},z=r.detailed_records||{};
 const pair=(x:any)=>x?`${x.name_a} — ${x.name_b} • ${x.n} meczów (${x.aw}:${x.bw}${x.d?`, ${x.d} remisów`:''})`:'—';
 return <View style={{gap:10}}>{e?<ErrorBox message={e}/>:null}{d&&!Object.keys(r).length?<Card><Muted>Rekordy pojawią się po pierwszych oficjalnych meczach.</Muted></Card>:null}{Object.keys(r).length?<>
  <Rec icon="🏆" title="Najwięcej tytułów" value={r.most_titles?`${r.most_titles.name} — ${r.most_titles.titles}`:'—'}/>
  <Rec icon="🥈" title="Najwięcej finałów" value={r.most_finals?`${r.most_finals.name} — ${r.most_finals.finals}`:'—'}/>
  <Rec icon="✅" title="Najwięcej zwycięstw" value={r.most_wins?`${r.most_wins.name} — ${r.most_wins.w}`:'—'}/>
  <Rec icon="⚽" title="Najwięcej goli" value={r.most_goals?`${r.most_goals.name} — ${r.most_goals.gf}`:'—'}/>
  <Rec icon="📈" title="Najlepsza skuteczność" value={r.best_win_pct?`${r.best_win_pct.name} — ${(100*r.best_win_pct.w/Math.max(1,r.best_win_pct.w+r.best_win_pct.d+r.best_win_pct.l)).toFixed(1)}%`:'—'} sub="Minimum 10 oficjalnych meczów."/>
  <Rec icon="🔥" title="Najdłuższa seria zwycięstw" value={nameVal(r.win_streak)}/>
  <Rec icon="🛡️" title="Najdłużej bez porażki" value={nameVal(r.unbeaten_streak)}/>
  <Rec icon="💥" title="Najwyższe zwycięstwo" value={r.biggest_win?`${r.biggest_win.home} ${r.biggest_win.score} ${r.biggest_win.away}`:'—'} sub={r.biggest_win?`Różnica ${r.biggest_win.margin} bramek.`:undefined}/>
  <Rec icon="🎆" title="Najbardziej bramkowy mecz" value={r.highest_scoring?`${r.highest_scoring.home} ${r.highest_scoring.score} ${r.highest_scoring.away}`:'—'} sub={r.highest_scoring?`${r.highest_scoring.goals} goli. Obrona miała wolne.`:undefined}/>
  <Rec icon="🎯" title="Najwięcej goli w jednym turnieju" value={nameVal(r.goals_one_tournament)}/>
  <Rec icon="👑" title="Tytuły z rzędu" value={nameVal(r.consecutive_titles)}/>
  <Rec icon="🤝" title="Najczęstsza rywalizacja" value={pair(r.most_frequent_h2h)}/>
  <Rec icon="⚖️" title="Najbardziej wyrównana rywalizacja" value={pair(r.balanced_rivalry)}/>
  <Rec icon="😈" title="Największa dominacja H2H" value={pair(r.h2h_dominance)}/>
  {z.fastest_goal?<Rec icon="⚡" title="Najszybszy gol" value={`${z.fastest_goal.footballer} — ${z.fastest_goal.minute_label}'`} sub={`${z.fastest_goal.player_name} • ${z.fastest_goal.match}`}/>:null}
  {z.latest_goal?<Rec icon="⏰" title="Najpóźniejszy gol" value={`${z.latest_goal.footballer} — ${z.latest_goal.minute_label}'`} sub={`${z.latest_goal.player_name} • ${z.latest_goal.match}`}/>:null}
  {z.fastest_hat_trick?<Rec icon="🎩" title="Najszybszy hat-trick" value={`${z.fastest_hat_trick.footballer} — ${z.fastest_hat_trick.duration} min`} sub={`${z.fastest_hat_trick.from_label}' → ${z.fastest_hat_trick.to_label}' • ${z.fastest_hat_trick.match}`}/>:null}
  {z.biggest_comeback?<Rec icon="🔄" title="Największy comeback" value={`${z.biggest_comeback.player_name} • z -${z.biggest_comeback.deficit}`} sub={z.biggest_comeback.match}/>:null}
  {z.biggest_blown_lead?<Rec icon="🫠" title="Największy wypuszczony wynik" value={`${z.biggest_blown_lead.player_name} • prowadził +${z.biggest_blown_lead.lead}`} sub={z.biggest_blown_lead.match}/>:null}
 </>:null}</View>;
}

function ProfileModal({id,onClose}:{id:string|null;onClose:()=>void}){
 const [d,setD]=useState<any>(null),[e,setE]=useState(''),[openBadges,setOpenBadges]=useState<Record<string,boolean>>({});
 useEffect(()=>{if(id){setD(null);setE('');api.player(id).then(setD).catch(x=>setE(x.message))}},[id]);
 const p=d?.profile||{},a=d?.achievement||{},aw=d?.awards||[],ev=d?.event_stats||{},trophy=d?.trophy_case||{};
 const h2h=(x:any)=>x?`${x.name} • ${x.w}W ${x.d}R ${x.l}P • ${x.gf}:${x.ga}`:'';
 return <Modal visible={!!id} animationType="slide" onRequestClose={onClose}><View style={s.modal}><View style={s.head}><Text style={s.pageTitle}>{p.name||'Profil gracza'}</Text><Pressable onPress={onClose}><Text style={s.close}>×</Text></Pressable></View><ScrollView contentContainerStyle={s.pad}>{e?<ErrorBox message={e}/>:null}{d?<>
  <Card style={s.profileHero}><Text style={{fontSize:42}}>👤</Text><Text style={s.profileName}>{p.name}</Text><Muted center>{p.matches??0} meczów • {p.win_pct??0}% zwycięstw</Muted><Text style={s.form}>{(p.form||[]).join(' ')||'—'}</Text></Card>
  <View style={s.metrics}><Metric value={p.titles??0} label="Tytuły"/><Metric value={p.finals??0} label="Finały"/><Metric value={p.gf??0} label="Gole"/><Metric value={p.gd>=0?`+${p.gd}`:p.gd??0} label="Bilans"/></View>
  {p.most_frequent||p.favorite||p.nemesis?<Card><Text style={s.cardTitle}>⚔️ Rywale</Text>{p.most_frequent?<Text style={s.line}>Najczęstszy: {h2h(p.most_frequent)}</Text>:null}{p.favorite?<Text style={s.line}>Ulubiony: {h2h(p.favorite)}</Text>:null}{p.nemesis?<Text style={s.line}>Nemesis: {h2h(p.nemesis)}</Text>:null}</Card>:null}
  {(p.teams||[]).length?<Card><Text style={s.cardTitle}>🏟️ Drużyny</Text>{p.teams.slice(0,8).map((x:any)=><Text key={x.team} style={s.line}>{x.team} • {x.matches} M • {x.win_pct}% W • {x.gf}:{x.ga}</Text>)}</Card>:null}
  {aw.length?<Card><Text style={s.cardTitle}>🏆 Awards</Text>{aw.map((x:any,i:number)=><Text key={i} style={s.line}>{x.year} • {x.title}</Text>)}</Card>:null}
  <Card><Text style={s.cardTitle}>🎖️ Odznaki</Text><Muted>Dotknij odznaki, żeby zobaczyć, za co wpadła.</Muted>{(a?.unlocked||a?.achievements||[]).map((x:any,i:number)=>{const key=String(x.key||i),open=!!openBadges[key];return <Pressable key={key} onPress={()=>setOpenBadges(z=>({...z,[key]:!z[key]}))} style={s.badge}><Text style={s.line}>{x.icon||'🏅'} <Text style={{fontWeight:'900'}}>{x.title||x.name}</Text> {open?'▲':'▼'}</Text>{open?<Muted>{x.description||x.desc||x.detail||''}{x.earned_at?`\n${fmtDate(x.earned_at)}`:''}</Muted>:null}</Pressable>})}{(a?.locked||[]).length?<Muted>Niezdobyte: {(a.locked||[]).map((x:any)=>x.title||x.name).join(' • ')}</Muted>:null}</Card>
  {ev.coverage_matches?<Card><Text style={s.cardTitle}>🎮 Szczegółowe zdarzenia</Text><Muted>Dane z meczów, w których zapisano dokładny przebieg.</Muted><View style={s.metrics}><Metric value={ev.coverage_matches} label="Mecze z przebiegiem"/><Metric value={`🟨 ${ev.yellow_cards} • 🟥 ${ev.red_cards}`} label="Kartki"/><Metric value={`${ev.penalties_scored}/${ev.penalties_awarded}`} label="Karne w meczu"/><Metric value={ev.own_goals} label="Samobóje"/></View>{ev.fastest_goal?<Text style={s.line}>⚡ Najszybszy gol: {ev.fastest_goal.footballer_name} • {ev.fastest_goal.minute_label}'</Text>:null}{ev.latest_goal?<Text style={s.line}>⏰ Najpóźniejszy gol: {ev.latest_goal.footballer_name} • {ev.latest_goal.minute_label}'</Text>:null}</Card>:null}
  {(trophy.milestones||[]).length?<Card><Text style={s.cardTitle}>💎 Kamienie milowe</Text>{trophy.milestones.map((x:any,i:number)=><Text key={i} style={s.line}>{x.icon||'💎'} {x.title} • {fmtDate(x.earned_at)}</Text>)}</Card>:null}
 </>:<Text style={s.sub}>Ładowanie…</Text>}</ScrollView></View></Modal>;
}

function Players({open}:{open:(id:string)=>void}){const [d,setD]=useState<any>(null);useEffect(()=>{api.playerStats().then(setD).catch(()=>{})},[]);return <View style={{gap:8}}>{(d?.players||[]).map((p:any)=><Pressable key={p.player_id} onPress={()=>open(p.player_id)}><Card style={s.personRow}><View><Text style={s.name}>{p.name}</Text><Text style={s.sub}>{p.matches} meczów • 🏆 {p.titles}</Text></View><Text style={s.arrow}>›</Text></Card></Pressable>)}</View>}

function Teams(){const [teams,setTeams]=useState<any[]>([]),[scorers,setScorers]=useState<any[]>([]),[mode,setMode]=useState<'teams'|'scorers'>('teams');useEffect(()=>{api.teamStats().then(x=>setTeams(x.teams||[]));api.scorerStats().then(x=>setScorers(x.scorers||[]))},[]);return <View style={{gap:10}}><HScroll><Chip label="🏟️ Drużyny" active={mode==='teams'} onPress={()=>setMode('teams')}/><Chip label="⚽ Strzelcy EA FC" active={mode==='scorers'} onPress={()=>setMode('scorers')}/></HScroll>{mode==='teams'?teams.map((x:any,i)=><Card key={x.team||i}><View style={s.between}><Text style={s.name}>{i+1}. {x.team}</Text><Pill text={`${x.rating??50}`} tone="blue"/></View><Text style={s.sub}>{x.matches??x.m??0} meczów • {x.w??0}W {x.d??0}R {x.l??0}P • {x.gf??0}:{x.ga??0} • {x.win_pct??0}%</Text></Card>):scorers.map((x:any,i)=><Card key={`${x.name}-${i}`}><View style={s.between}><Text style={s.name}>{i+1}. {x.name}</Text><Text style={s.goals}>{x.goals} ⚽</Text></View><Text style={s.sub}>{x.teams||''} • mecze z golem: {x.matches_scored??0}</Text></Card>)}</View>}

function Finance({controller}:{controller:boolean}){
 const [data,setData]=useState<any>(null),[selected,setSelected]=useState<string[]>([]),[settlement,setSettlement]=useState<any>(null),[err,setErr]=useState('');
 const load=()=>api.finance().then(setData).catch(x=>setErr(x.message));useEffect(()=>{void load()},[]);const items=data?.items||[];const toggle=(id:string)=>setSelected(x=>x.includes(id)?x.filter(y=>y!==id):[...x,id]);
 const calc=async()=>{try{setSettlement(await api.settlement(selected))}catch(e:any){setErr(e.message)}};
 const mark=async()=>{try{const ids=(settlement?.tournaments||[]).filter((x:any)=>!x.settled).map((x:any)=>x.id);await api.markSettled(ids,true);await load();setSettlement(await api.settlement(selected))}catch(e:any){setErr(e.message)}};
 const png=async(mode:'share'|'save')=>{try{await getPng(`/api/v1/exports/settlement.png?ids=${encodeURIComponent(selected.join(','))}`,'fifa-night-rozliczenie.png',mode)}catch(e:any){Alert.alert('Błąd',e.message)}};
 return <View style={{gap:10}}>{err?<ErrorBox message={err}/>:null}<Card><Text style={s.cardTitle}>💰 Rozliczenia</Text><Muted>Wybierz rozgrywki, a aplikacja policzy końcowe przelewy. Jackpot: {((data?.jackpot_cents||0)/100).toFixed(2)} zł.</Muted></Card>{items.map((x:any)=><Pressable key={x.id} onPress={()=>toggle(x.id)}><Card style={selected.includes(x.id)?s.selected:null}><View style={s.between}><Text style={s.name}>{x.format_key==='duel1v1'?'⚔️ 1 VS 1':`🏆 FIFA Night${x.official_no?` #${x.official_no}`:''}`}</Text><Pill text={x.settled?'ROZLICZONE':'DO ROZLICZENIA'} tone={x.settled?'green':'amber'}/></View><Text style={s.sub}>{fmtDate(x.completed_at||x.created_at)} • {Number(x.stake_per_player||0).toFixed(2)} zł/os. • {x.champion_name||'—'}</Text></Card></Pressable>)}{selected.length?<Btn title="🧮 POLICZ ROZLICZENIE" onPress={calc}/>:null}{settlement?<Card><Text style={s.cardTitle}>💳 Kto komu przelewa</Text>{(settlement.transfers||[]).length?(settlement.transfers||[]).map((x:any,i:number)=><Text style={s.transfer} key={i}>{x.from_name} → {x.to_name}: {(x.amount_cents/100).toFixed(2)} zł</Text>):<Text style={s.line}>✅ Brak przelewów. Portfele mogą odetchnąć.</Text>}{settlement.pending_jackpot_cents?<Text style={s.warn}>🎰 Jackpot do przeniesienia: {(settlement.pending_jackpot_cents/100).toFixed(2)} zł</Text>:null}<View style={s.two}><View style={{flex:1}}><Btn title="💾 ZAPISZ PNG" tone="secondary" onPress={()=>png('save')}/></View><View style={{flex:1}}><Btn title="📤 UDOSTĘPNIJ" tone="secondary" onPress={()=>png('share')}/></View></View>{controller&&(settlement.tournaments||[]).some((x:any)=>!x.settled)?<Btn title="✅ OZNACZ JAKO ROZLICZONE" onPress={mark}/>:null}</Card>:null}</View>;
}

const deLayout:any={double4:{wb:[[1,2],[4]],lb:[[3],[5]],final:[6]},double5:{wb:[[1,2],[3],[5]],lb:[[4],[6],[7]],final:[8]},double6:{wb:[[1,2],[3,4],[7]],lb:[[5],[6],[8],[9]],final:[10]},double7:{wb:[[1,2,3],[4,5],[9]],lb:[[6],[7,8],[10],[11]],final:[12]},double8:{wb:[[1,2,3,4],[5,6],[11]],lb:[[7,8],[9,10],[12],[13]],final:[14]}};
const eventLabel=(x:string)=>({normal_goal:'gol',penalty_goal:'gol z karnego',penalty_miss:'niewykorzystany karny',own_goal:'samobój',yellow_card:'żółta kartka',red_card:'czerwona kartka',injury:'kontuzja',substitution:'zmiana'} as any)[x]||x;
function historyScore(m:any){
 if(m.match_status==='skipped')return 'POMINIĘTY';
 if(m.home_score==null)return '—';
 let value=`${m.home_score}:${m.away_score}`;
 if(m.home_penalties!=null&&m.away_penalties!=null)value+=` (k. ${m.home_penalties}:${m.away_penalties})`;
 return value;
}
function eventMinute(e:any){const raw=String(e?.minute_label??e?.minute??'').trim().replace(/[’′']/g,'');return raw?`${raw}'`:'—'}
function eventDetails(e:any){
 if(e?.synthetic_de)return 'samobój techniczny DE';
 if(e?.event_type==='substitution')return `${e.footballer_name||'—'} ↔ ${e.related_footballer_name||'—'}`;
 return String(e?.footballer_name||'—');
}
function HistoryMatch({m}:{m:any}){const [open,setOpen]=useState(false);return <Card><Pressable onPress={()=>setOpen(!open)}><View style={s.between}><View style={{flex:1}}><Text style={s.line}>M{m.match_no} • {m.stage_label}</Text><Text style={s.name}>{m.home_name||'—'} {historyScore(m)} {m.away_name||'—'}</Text><Text style={s.sub}>{m.home_team||'—'} vs {m.away_team||'—'}</Text></View><Text style={s.arrow}>{open?'⌃':'⌄'}</Text></View></Pressable>{open?<View style={{gap:7}}>{m.match_status==='skipped'?<Muted>Pominięty — układ turnieju był już rozstrzygnięty.</Muted>:m.home_score==null?<Muted>Nie rozegrano.</Muted>:<>{(m.scorers||[]).length?<><Text style={s.small}>STRZELCY</Text>{m.scorers.map((x:any,i:number)=><Text key={i} style={s.line}>⚽ {x.scorer_name} ×{x.goals} • {x.team_name}</Text>)}</>:<Muted>Strzelcy nie zostali wpisani.</Muted>}{(m.events||[]).length?<><Text style={s.small}>PRZEBIEG</Text>{m.events.map((e:any,i:number)=><Text key={i} style={s.line}>{eventMinute(e)} • {eventLabel(e.event_type)} • {eventDetails(e)}{e.actor_player_name?` • ${e.actor_player_name}`:''}</Text>)}</>:null}</>}</View>:null}</Card>}
function HistoryDetail({id,controller,onClose,onDeleted}:{id:string|null;controller:boolean;onClose:()=>void;onDeleted:()=>void}){
 const [d,setD]=useState<any>(null),[view,setView]=useState<'list'|'tree'>('list'),[err,setErr]=useState('');useEffect(()=>{if(id){setD(null);setErr('');api.historyDetail(id).then(setD).catch(x=>setErr(x.message))}},[id]);const t=d?.tournament||{},a=d?.archive||{},matches=d?.matches||[],officialNo=a.official_no;
 const png=async(mode:'share'|'save')=>{try{await getPng(`/api/v1/exports/tournament/${id}/summary.png`,`fifa-night-${officialNo||'turniej'}.png`,mode)}catch(e:any){Alert.alert('Błąd',e.message)}};
 const del=()=>Alert.alert('Usunąć z Historii?',t.format_key==='duel1v1'?'Usuniesz cały mecz 1 VS 1 i jego statystyki.':'Usuniesz cały turniej wraz ze wszystkimi jego meczami i statystykami.',[{text:'Anuluj'},{text:'Usuń',style:'destructive',onPress:async()=>{try{await api.deleteHistory(id!);onDeleted();onClose()}catch(e:any){Alert.alert('Błąd',e.message)}}}]);
 const Br=()=>{const lay=deLayout[t.format_key],mm:any={};matches.forEach((m:any)=>mm[m.match_no]=m);if(!lay)return null;const lane=(title:string,rounds:number[][])=><View style={{gap:7}}><Text style={s.small}>{title}</Text><ScrollView horizontal><View style={{flexDirection:'row',gap:9}}>{rounds.map((r,i)=><View key={i} style={{width:250,gap:7}}><Text style={s.sub}>Runda {i+1}</Text>{r.map(n=>mm[n]?<HistoryMatch key={n} m={mm[n]}/>:null)}</View>)}</View></ScrollView></View>;return <View style={{gap:13}}>{lane('🌿 WINNERS',lay.wb)}{lane('🩸 LOSERS',lay.lb)}<Text style={s.small}>🏆 WIELKI FINAŁ</Text>{lay.final.map((n:number)=>mm[n]?<HistoryMatch key={n} m={mm[n]}/>:null)}</View>};
 return <Modal visible={!!id} animationType="slide" onRequestClose={onClose}><View style={s.modal}><View style={s.head}><View><Text style={s.pageTitle}>{t.format_key==='duel1v1'?'1 VS 1':`FIFA Night${officialNo?` #${officialNo}`:''}`}</Text><Text style={s.sub}>{fmtDate(t.completed_at||t.created_at)} • {t.format_label||d?.format_label}</Text></View><Pressable onPress={onClose}><Text style={s.close}>×</Text></Pressable></View><ScrollView contentContainerStyle={s.pad}>{err?<ErrorBox message={err}/>:null}{d?<><Card style={t.unfinished?s.unfinished:null}><View style={s.between}><Pill text={t.unfinished?'⚠️ NIEDOKOŃCZONY':t.is_test?'🧪 TEST':'✅ ZAKOŃCZONY'} tone={t.unfinished?'amber':t.is_test?'amber':'green'}/>{d.summary?.champion?<Text style={s.titleNo}>🏆 {d.summary.champion}</Text>:null}</View><Text style={s.sub}>{(d.players||[]).map((p:any)=>`${p.name} • ${p.team||'—'}`).join('\n')}</Text></Card>{Object.keys(d.standings||{}).length?<Card><Text style={s.cardTitle}>📊 Tabela / grupy</Text>{Object.entries(d.standings).map(([g,rows]:any)=><View key={g}><Text style={s.small}>{g==='L'?'LIGA':`GRUPA ${g}`}</Text>{rows.map((r:any,i:number)=><Text key={r.player_id} style={s.line}>{i+1}. {r.name} — {r.pts} pkt ({r.gd>0?'+':''}{r.gd})</Text>)}</View>)}</Card>:null}{t.format_key?.startsWith('double')?<HScroll><Chip label="📋 Lista" active={view==='list'} onPress={()=>setView('list')}/><Chip label="🌳 Drzewko" active={view==='tree'} onPress={()=>setView('tree')}/></HScroll>:null}{view==='tree'&&t.format_key?.startsWith('double')?<Br/>:<View style={{gap:8}}>{matches.map((m:any)=><HistoryMatch key={m.match_no} m={m}/>)}</View>}{t.status==='completed'?<Card><Text style={s.cardTitle}>🖼️ Podsumowanie</Text><View style={s.two}><View style={{flex:1}}><Btn title="💾 ZAPISZ PNG" tone="secondary" onPress={()=>png('save')}/></View><View style={{flex:1}}><Btn title="📤 UDOSTĘPNIJ" tone="secondary" onPress={()=>png('share')}/></View></View></Card>:null}{controller?<Btn title={t.format_key==='duel1v1'?'🗑️ USUŃ TEN MECZ 1 VS 1':'🗑️ USUŃ CAŁY TURNIEJ'} tone="danger" onPress={del}/>:<Muted>Usuwanie Historii jest dostępne po przejęciu sterowania.</Muted>}</>:<Text style={s.sub}>Ładowanie…</Text>}</ScrollView></View></Modal>;
}
function History({controller}:{controller:boolean}){const [items,setItems]=useState<any[]>([]),[tests,setTests]=useState(false),[selected,setSelected]=useState<string|null>(null),[err,setErr]=useState('');const load=()=>api.history(tests).then(x=>setItems(x.items||[])).catch(x=>setErr(x.message));useEffect(()=>{void load()},[tests]);return <View style={{gap:9}}>{err?<ErrorBox message={err}/>:null}<ToggleRow label="Pokaż także turnieje testowe" value={tests} onChange={setTests}/>{items.map((x:any)=><Pressable key={x.id} onPress={()=>setSelected(x.id)}><Card style={x.unfinished?s.unfinished:null}><View style={s.between}><Text style={s.name}>{x.is_duel?'⚔️ 1 VS 1':`🏆 FIFA Night${x.official_no?` #${x.official_no}`:''}`}</Text><Text style={s.arrow}>›</Text></View><Text style={s.sub}>{fmtDate(x.completed_at||x.created_at)} • {x.is_duel?'2 graczy':`${x.player_count} graczy`} • {x.format_label}</Text><View style={{marginTop:3}}><Pill text={x.unfinished?'NIEDOKOŃCZONY':x.is_test?'TEST':x.champion_name?`MISTRZ: ${x.champion_name}`:'ZAKOŃCZONY'} tone={x.unfinished?'amber':x.is_test?'amber':'green'}/></View></Card></Pressable>)}<HistoryDetail id={selected} controller={controller} onClose={()=>setSelected(null)} onDeleted={load}/></View>}

export default function StatsScreen({controller}:{controller:boolean}){const [tab,setTab]=useState<Tab>('ranking'),[player,setPlayer]=useState<string|null>(null);return <ScrollView contentContainerStyle={s.pad} keyboardShouldPersistTaps="handled"><Text style={s.pageTitle}>Statystyki</Text><HScroll>{tabs.map(x=><Chip key={x.k} label={x.l} active={tab===x.k} onPress={()=>setTab(x.k)}/>)}</HScroll>{tab==='ranking'?<Ranking open={setPlayer}/>:tab==='records'?<Records/>:tab==='players'?<Players open={setPlayer}/>:tab==='teams'?<Teams/>:tab==='finance'?<Finance controller={controller}/>:<History controller={controller}/>}<ProfileModal id={player} onClose={()=>setPlayer(null)}/></ScrollView>}

const s=StyleSheet.create({pad:{padding:15,paddingBottom:48,gap:11},pageTitle:{color:colors.text,fontSize:27,fontWeight:'900'},cardTitle:{color:colors.text,fontSize:16,fontWeight:'900'},rank:{flexDirection:'row',alignItems:'center',gap:11},rankNo:{width:28,color:colors.green,fontSize:23,fontWeight:'900'},name:{color:colors.text,fontSize:16,fontWeight:'900'},sub:{color:colors.muted,fontSize:11,lineHeight:16,marginTop:2},titleNo:{color:colors.amber,fontWeight:'900',textAlign:'right'},win:{color:colors.green,fontWeight:'800',fontSize:10,textAlign:'right',marginTop:3},metrics:{flexDirection:'row',flexWrap:'wrap',gap:8},personRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},arrow:{color:colors.muted,fontSize:25},modal:{flex:1,backgroundColor:colors.bg,paddingTop:38},head:{paddingHorizontal:15,paddingBottom:9,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},close:{color:colors.text,fontSize:30},profileHero:{alignItems:'center'},profileName:{color:colors.text,fontSize:28,fontWeight:'900'},form:{color:colors.green,fontSize:14,fontWeight:'900',letterSpacing:3},line:{color:colors.text,fontSize:12,lineHeight:19},badge:{paddingVertical:9,borderTopWidth:1,borderTopColor:'#172a3d'},between:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},goals:{color:colors.green,fontSize:18,fontWeight:'900'},selected:{borderColor:'#2d9a74',backgroundColor:'#0e2d2a'},two:{flexDirection:'row',gap:8},transfer:{color:colors.green,fontSize:14,fontWeight:'900',lineHeight:22},warn:{color:colors.amber,fontSize:12,lineHeight:18},small:{color:colors.muted,fontSize:10,fontWeight:'900',letterSpacing:1},unfinished:{borderColor:'#7b6415',backgroundColor:'#2b260f'},recordHead:{flexDirection:'row',gap:12,alignItems:'center'},recordIcon:{fontSize:28},recordValue:{color:colors.green,fontSize:14,fontWeight:'900',marginTop:4}});
